name: edumips64
version: '1.2.10'
summary: A free visual and cross-platform MIPS64 CPU simulator.
description: EduMIPS64 is a free MIPS64 visual simulator and debugger, used as a teaching tool in Computer Architecture courses.
grade: stable

base: core18
confinement: strict

parts:
  edumips64:
    plugin: gradle
    source: https://github.com/edumips64/edumips64.git
    gradle-version: '7.4'
    gradle-options: [jar]
    override-build: |
      snapcraftctl build
    build-packages:
      - git
      - openjdk-17-jdk
      - python3
      - python3-pip
      # Needed to build pillow, a rst2pdf dependency.
      - python3-dev
      - zlib1g-dev
      - libjpeg-dev
      - libtiff-dev
      - libfreetype6-dev
      - liblcms2-dev
      - libwebp-dev
      - libopenjp2-7-dev
      - libraqm-dev
      - libxcb-xfixes0-dev
    stage-packages:
      # This is required because snap ships the headless version by default,
      # which lacks splashscreen support.
      - openjdk-17-jre

  scripts:
    plugin: dump
    source: scripts

apps:
  edumips64:
    desktop: edumips64.desktop
    command: edumips64-snap-wrapper.sh
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-17-openjdk-amd64
      PATH: $JAVA_HOME/jre/bin:$PATH
    plugs:
      - home
      - x11
      - desktop

  edumips64-cli:
    command: edumips64-snap-wrapper.sh --headless
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-17-openjdk-amd64
      PATH: $JAVA_HOME/jre/bin:$PATH
    plugs:
      - home
