package(default_visibility = ["//visibility:public"])

java_test(
    name = "ConfigStoreTest",
    size = "small",
    srcs = ["ConfigStoreTest.java"],
    deps = [
        "//src/main/java/org/edumips64/utils:config",
        "//src/test/java/org/edumips64:basetest",
    ],
)