package(default_visibility = ["//visibility:public"])

java_test(
    name = "FPInstructionUtilsTest",
    size = "small",
    srcs = ["FPInstructionUtilsTest.java"],
    deps = [
        "//src/main/java/org/edumips64/core:exceptions",
        "//src/main/java/org/edumips64/core:fcsr",
        "//src/main/java/org/edumips64/core/fpu:exceptions",
        "//src/main/java/org/edumips64/core/fpu:fpinstructionutils",
        "//src/test/java/org/edumips64:basetest",
    ],
)
