<?xml version="1.0" encoding="UTF-8"?>
<!--generated by JHelpDev Version: 0.61, 18 January 2006, see jhelpdev.sourceforge.net--><!DOCTYPE helpset PUBLIC "-//Sun Microsystems Inc.//DTD JavaHelp HelpSet Version 2.0//EN" "http://java.sun.com/products/javahelp/helpset_2_0.dtd">

<helpset version="1.0">
 <title>Help </title>
 <maps>
  <homeID>
top
  </homeID>
  <mapref location="Map.jhm"/>

 </maps>
 <view>
  <name>
TOC
  </name>
  <label>
TOC 
  </label>
  <type>
javax.help.TOCView
  </type>
  <data>
edumips64TOC.xml
  </data>
 </view>
 <view>
  <name>
Index
  </name>
  <label>
Index 
  </label>
  <type>
javax.help.IndexView
  </type>
  <data>
edumips64Index.xml
  </data>
 </view>
 <view>
  <name>
Search
  </name>
  <label>
Search 
  </label>
  <type>
javax.help.SearchView
  </type>
  <data engine="com.sun.java.help.search.DefaultSearchEngine">
JavaHelpSearch
  </data>
 </view>
</helpset>
