package(default_visibility = ["//visibility:public"])

filegroup(
    name = "javahelp",
    srcs = glob(["javahelp/**/*"]),
)

filegroup(
    name = "makefile",
    srcs = ["src/Makefile"],
)

filegroup(
    name = "src",
    srcs = glob(["src/*.rst"]) + ["src/conf.py"],
)
