<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE helpset 
  PUBLIC "-//Sun Microsystems Inc.//DTD JavaHelp HelpSet Version 2.0//EN" 
         "http://java.sun.com/products/javahelp/helpset_2_0.dtd">


<!--This Helpset was first generated by JHelpDev 0.63 (jhelpdev.sourceforge.net),
    and then modified by Andrea Spadaccini using as a guideline the JavaHelp
    System User's Guide.-->

<helpset version="2.0">
    <title>Manuale di EduMIPS64</title>

    <maps>
        <homeID>top</homeID>
        <mapref location="Map.jhm"/>
    </maps>

    <view xml:lang="it">
        <name>TOC</name>
        <label>Contenuti</label>
        <type>javax.help.TOCView</type>
        <data>EduMIPS64TOC.xml</data>
    </view>

    <presentation default="true" displayviewimages="false" xml:lang="it">
        <name>main window</name>
        <size width="400" height="400" />
        <location x="200" y="200" />
        <title>Manuale di EduMIPS64</title>
        <toolbar>
            <helpaction image = "img_back">javax.help.BackAction</helpaction>
            <helpaction image = "img_fwd">javax.help.ForwardAction</helpaction>
            <helpaction image = "img_home">javax.help.HomeAction</helpaction>
            <helpaction image = "img_print">javax.help.PrintAction</helpaction>
        </toolbar>
    </presentation>
</helpset>
