name: Build all / deploy web app to dev environment

on:
  pull_request:
    branches:
      - master

jobs:
  build-desktop:
    name: Build desktop app and docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Install docs dependencies
        run: pip3 install -r docs/requirements.txt -U
      - name: Read version from gradle.properties
        id: read_version
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: 'gradle.properties'
          property: 'version'

      # Compile the code, run unit tests, upload code coverage results.
      - name: Compile Java code
        run: ./gradlew compileJava
      - name: Run unit tests
        run: ./gradlew check
      - name: Codecov
        uses: codecov/codecov-action@v2.0.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      # Build docs (PDF and HTML for the in-app help)
      - name: Build all docs
        run: ./gradlew allDocs

      # Build JAR files.
      - name: Build JAR
        run: ./gradlew jar

      # Upload artifacts (manuals and JARs)
      - name: Upload English Manual PDF
        uses: actions/upload-artifact@v2.2.4
        with:
          name: English manual (PDF)
          path: ./build/docs/en/pdf/EduMIPS64.pdf
      - name: Upload Italian Manual PDF
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Italian manual (PDF)
          path: ./build/docs/it/pdf/EduMIPS64.pdf

      - name: Upload JAR
        uses: actions/upload-artifact@v2.2.4
        with:
          name: JAR
          path: ./build/libs/edumips64-${{ steps.read_version.outputs.value }}.jar

  build-web:
    name: Build web app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build Web UI
        run: ./gradlew war
      - name: Set up Node.JS 12
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm run build

      - uses: actions/upload-artifact@v2
        with:
          name: web
          path: build/gwt/war/edumips64
  
  deploy-web:
    name: Deploy web app
    runs-on: ubuntu-latest
    needs: build-web
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: web
          path: build/gwt/war/edumips64
      # Deploy the code on Github Pages.
      - name: Start deployment
        uses: bobheadxi/deployments@v0.6.0
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: ${{ github.event.pull_request.number }}
          ref: ${{ github.head_ref }}
      - name: Copy files to run directory
        run: mkdir -p pr/${{ github.event.pull_request.number }} && cp -r build/gwt/war/edumips64/* pr/${{ github.event.pull_request.number }}
      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: master
          build_dir: pr/
          repo: EduMIPS64/web.edumips.org
          keep_history: true
          commit_message: Deploy code for PR ${{ github.event.pull_request.number }}
          fqdn: web.edumips.org
        env:
          GH_PAT: ${{ secrets.PAT_WEBUI }}
      - name: Update deployment status
        uses: bobheadxi/deployments@v0.6.0
        if: always() && github.head_ref
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: https://web.edumips.org/${{github.event.pull_request.number}}

  test-web:
    name: Test web app
    runs-on: ubuntu-latest
    needs: deploy-web
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.JS 12
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - run: npm install
      # Run tests against the deployed code.
      - name: Run web tests against deployed code
        uses: nick-invision/retry@v2
        env:
          PLAYWRIGHT_TARGET_URL: 'https://web.edumips.org/${{ github.event.pull_request.number }}'
        with:
          max_attempts: 10
          timeout_minutes: 2
          retry_on: error
          command: npm run test

